"""Build an M2 V2 evidence directory. Does not set m3_ready."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from feedingrobot.controllers.acceptance import SCHEMA_VERSION, SCOPE_NAME, collect_inputs, evaluate_evidence, required_case_ids
from feedingrobot.sim.model import repo_root


def _sha256(path: Path) -> str:
    import hashlib

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _evidence_manifest(case_dir: Path) -> dict:
    rows = []
    for path in sorted(case_dir.iterdir()):
        if path.is_file():
            rows.append({"path": f"cases/{path.name}", "sha256": _sha256(path)})
    return {"files": rows}


def main():
    parser = argparse.ArgumentParser(description="M2 acceptance runner")
    parser.add_argument("--scope", default="full", choices=("fixes-v1", "fixes-v2", "full"))
    parser.add_argument("--scene-config", default="configs/m1_scene.json")
    parser.add_argument("--controller-config", default="configs/m2_controller.json")
    parser.add_argument("--acceptance-config", default="configs/m2_acceptance.json")
    parser.add_argument("--m1-baseline", default="outputs/m1/acceptance/m1-fix-v3b")
    parser.add_argument("--m1-regression", default="outputs/m1/acceptance/m2-fix-v2-regression")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    if args.scope == "fixes-v1":
        raise SystemExit("fixes-v1 is not a V2 certification and is not generated by this entry")
    if args.scope != "fixes-v2":
        raise SystemExit("full M2 matrix is not runnable from this entry; use --scope fixes-v2")
    root = repo_root()
    out = Path(args.output)
    if not out.is_absolute():
        out = root / out
    if out.exists():
        raise SystemExit(f"refusing to overwrite {out}")
    out.mkdir(parents=True)
    case_dir = out / "cases"
    case_dir.mkdir()
    (out / "plots").mkdir()
    (out / "run.json").write_text(json.dumps({"incomplete": True, "started": datetime.now(timezone.utc).isoformat()}, indent=2))
    before = collect_inputs(root)
    (out / "input_hash_before.json").write_text(json.dumps(before, indent=2))
    execution_path = out / "execution.json"
    env = os.environ.copy()
    env["M1_EXECUTION_PATH"] = str(execution_path)
    env["M1_RUN_ID"] = out.name
    env["M2_EVIDENCE_DIR"] = str(case_dir)
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/test_m2_math.py", "tests/test_m2_tracking.py", "tests/test_m2_traj.py", "tests/test_m2_wrench.py", "tests/test_m2_guard.py", "tests/test_m2_fixes.py", "tests/test_m2_report.py", "tests/test_m2_v2.py", "-q"],
        cwd=root,
        capture_output=True,
        text=True,
        env=env,
    )
    (out / "pytest.txt").write_text(proc.stdout + "\n" + proc.stderr)
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr)
        raise SystemExit(proc.returncode)
    after = collect_inputs(root)
    (out / "input_hash_after.json").write_text(json.dumps(after, indent=2))
    (out / "controller_config.json").write_text((root / args.controller_config).read_text())
    (out / "acceptance_config.json").write_text((root / args.acceptance_config).read_text())
    (out / "environment.json").write_text(json.dumps({"python": sys.version}, indent=2))
    (out / "case_manifest.json").write_text(json.dumps({"cases": required_case_ids()}, indent=2))
    (out / "evidence_manifest.json").write_text(json.dumps(_evidence_manifest(case_dir), indent=2))
    baseline = root / args.m1_baseline
    regression = root / args.m1_regression
    (out / "baseline.json").write_text(json.dumps({"path": str(baseline), "report": str(baseline / "report.json")}, indent=2))
    (out / "m1_regression_binding.json").write_text(
        json.dumps(
            {
                "baseline_dir": str(baseline),
                "regression_dir": str(regression),
                "report_sha256": _sha256(regression / "report.json") if (regression / "report.json").is_file() else None,
            },
            indent=2,
        )
    )
    peaks = []
    for path in sorted(case_dir.glob("takeover-*.npz")):
        data = np.load(path)
        peaks.append({"case": path.stem, "max_abs_dq": float(np.max(np.abs(data["dq"]))), "max_abs_tau": float(np.max(np.abs(data["tau"])))})
    calibration = root / "docs" / "m2_calibration.md"
    text = calibration.read_text() if calibration.is_file() else ""
    text += "\n\n## V2 measured takeover\n\n" + "\n".join(
        f"- {row['case']}: max |dq| {row['max_abs_dq']:.6f} rad/s, max |tau| {row['max_abs_tau']:.6f} N m" for row in peaks
    ) + "\n"
    (out / "calibration.md").write_text(text)
    (out / "comparisons.json").write_text("{}\n")
    (out / "report.json").write_text("{}\n")
    (out / "run.json").write_text(json.dumps({"incomplete": False, "scope": SCOPE_NAME, "m3_ready": False}, indent=2))
    verdict = evaluate_evidence(out, check_workspace=True)
    (out / "comparisons.json").write_text(json.dumps(verdict.get("comparisons", {}), indent=2))
    report = {
        "schema_version": SCHEMA_VERSION,
        "scope": SCOPE_NAME,
        "incomplete": False,
        "fixes_passed": verdict["fixes_passed"],
        "m3_ready": False,
        "hybrid_force_status": "disabled",
        "evidence_valid": verdict["evidence_valid"],
        "remaining_m2_requirements": verdict["remaining_m2_requirements"],
        "reasons": verdict["reasons"],
        "pytest_returncode": proc.returncode,
    }
    (out / "report.json").write_text(json.dumps(report, indent=2))
    print(json.dumps({"pytest": proc.returncode, "output": str(out), "fixes_passed": verdict["fixes_passed"], "m3_ready": False, "reasons": verdict["reasons"][:12]}, indent=2))
    if not verdict["fixes_passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
