"""Build an M2 V6 evidence directory. Does not set m3_ready."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from feedingrobot.controllers.acceptance import SCHEMA_VERSION, SCOPE_NAME, V6_SECOND_STAGE_NODEIDS, collect_inputs, evaluate_evidence, required_case_ids
from feedingrobot.controllers.v3spec import RELEASE_SCORING_VERSION
from feedingrobot.controllers.v3spec import evidence_paths
from feedingrobot.sim.model import repo_root

FROZEN = {
    "scene-config": "configs/m1_scene.json",
    "controller-config": "configs/m2_controller.json",
    "acceptance-config": "configs/m2_acceptance.json",
}


def _sha256(path: Path) -> str:
    import hashlib

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _evidence_manifest(out: Path) -> dict:
    rows = []
    rels = list(evidence_paths())
    for extra in ("adversarial_execution.json", "adversarial_results.json"):
        if (out / extra).is_file() and extra not in rels:
            rels.append(extra)
    for rel in rels:
        path = out / rel
        if not path.is_file():
            raise SystemExit(f"missing evidence file {rel}")
        rows.append({"path": rel, "sha256": _sha256(path)})
    return {"files": rows}


def main():
    parser = argparse.ArgumentParser(description="M2 acceptance runner")
    parser.add_argument("--scope", default="full", choices=("fixes-v1", "fixes-v2", "fixes-v3", "fixes-v4", "fixes-v5", "fixes-v6", "full"))
    parser.add_argument("--scene-config", default="configs/m1_scene.json")
    parser.add_argument("--controller-config", default="configs/m2_controller.json")
    parser.add_argument("--acceptance-config", default="configs/m2_acceptance.json")
    parser.add_argument("--m1-baseline", default="outputs/m1/acceptance/m1-fix-v3b")
    parser.add_argument("--m1-regression", default="outputs/m1/acceptance/m2-fix-v6-regression")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    if args.scope in {"fixes-v1", "fixes-v2", "fixes-v3", "fixes-v4", "fixes-v5"}:
        raise SystemExit(f"{args.scope} is not a V6 certification and is not generated by this entry")
    if args.scope != "fixes-v6":
        raise SystemExit("full M2 matrix is not runnable from this entry; use --scope fixes-v6")
    if (args.scene_config, args.controller_config, args.acceptance_config) != (
        FROZEN["scene-config"],
        FROZEN["controller-config"],
        FROZEN["acceptance-config"],
    ):
        raise SystemExit("only the frozen scene, controller, and acceptance configs are accepted")
    root = repo_root()
    out = Path(args.output)
    if not out.is_absolute():
        out = root / out
    if out.exists():
        raise SystemExit(f"refusing to overwrite {out}")
    out.mkdir(parents=True)
    case_dir = out / "cases"
    case_dir.mkdir()
    (out / "plots").mkdir()
    (out / "run.json").write_text(json.dumps({"incomplete": True, "started": datetime.now(timezone.utc).isoformat()}, indent=2))
    before = collect_inputs(root)
    (out / "input_hash_before.json").write_text(json.dumps(before, indent=2))
    execution_path = out / "execution.json"
    env = os.environ.copy()
    env["M1_EXECUTION_PATH"] = str(execution_path)
    env["M1_RUN_ID"] = out.name
    env["M2_EVIDENCE_DIR"] = str(case_dir)
    for key in ("M2_V3_PACKAGE", "M2_V4_PACKAGE", "M2_V5_PACKAGE", "M2_V6_PACKAGE", "M2_V3_RESULTS", "M2_V4_RESULTS", "M2_V5_RESULTS", "M2_V6_RESULTS"):
        env.pop(key, None)
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/test_m2_math.py", "tests/test_m2_tracking.py", "tests/test_m2_traj.py", "tests/test_m2_wrench.py", "tests/test_m2_guard.py", "tests/test_m2_fixes.py", "tests/test_m2_report.py", "tests/test_m2_v2.py", "tests/test_m2_v5.py", "tests/test_m2_v6.py", "tests/test_m2_v6_r3.py", "-q"],
        cwd=root,
        capture_output=True,
        text=True,
        env=env,
    )
    (out / "pytest.txt").write_text(proc.stdout + "\n" + proc.stderr)
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr)
        raise SystemExit(proc.returncode)
    after = collect_inputs(root)
    (out / "input_hash_after.json").write_text(json.dumps(after, indent=2))
    (out / "controller_config.json").write_text((root / args.controller_config).read_text())
    (out / "acceptance_config.json").write_text((root / args.acceptance_config).read_text())
    (out / "environment.json").write_text(json.dumps({"python": sys.version}, indent=2))
    (out / "case_manifest.json").write_text(json.dumps({"cases": required_case_ids()}, indent=2))
    baseline = root / args.m1_baseline
    regression = root / args.m1_regression
    (out / "baseline.json").write_text(json.dumps({"path": str(baseline), "report": str(baseline / "report.json")}, indent=2))
    (out / "m1_regression_binding.json").write_text(
        json.dumps(
            {
                "baseline_dir": str(baseline),
                "regression_dir": str(regression),
                "report_sha256": _sha256(regression / "report.json") if (regression / "report.json").is_file() else None,
            },
            indent=2,
        )
    )
    peaks = []
    for path in sorted(case_dir.glob("takeover-*.npz")):
        data = np.load(path)
        peaks.append({"case": path.stem, "max_abs_dq": float(np.max(np.abs(data["dq"]))), "max_abs_tau": float(np.max(np.abs(data["tau_applied"])))})
    calibration = root / "docs" / "m2_calibration.md"
    text = calibration.read_text() if calibration.is_file() else ""
    text += "\n\n## V3 measured takeover\n\n" + "\n".join(
        f"- {row['case']}: max |dq| {row['max_abs_dq']:.6f} rad/s, max |tau| {row['max_abs_tau']:.6f} N m" for row in peaks
    ) + "\n"
    (out / "calibration.md").write_text(text)
    (out / "comparisons.json").write_text("[]\n")
    (out / "report.json").write_text("{}\n")
    (out / "evidence_manifest.json").write_text(json.dumps(_evidence_manifest(out), indent=2))
    (out / "run.json").write_text(json.dumps({"incomplete": False, "scope": SCOPE_NAME, "m3_ready": False}, indent=2))
    verdict = evaluate_evidence(out, check_workspace=True)
    (out / "comparisons.json").write_text(json.dumps(verdict.get("comparisons", []), indent=2))
    (out / "evidence_manifest.json").write_text(json.dumps(_evidence_manifest(out), indent=2))
    verdict = evaluate_evidence(out, check_workspace=True)
    if verdict["reasons"]:
        print(json.dumps(verdict["reasons"][:12], indent=2))
        raise SystemExit("core evidence failed before adversarial checks")
    adv_env = os.environ.copy()
    for key in ("M2_V3_PACKAGE", "M2_V4_PACKAGE", "M2_V5_PACKAGE", "M2_V6_PACKAGE"):
        adv_env.pop(key, None)
    adv_env["M2_V6_PACKAGE"] = str(out)
    adv_env["M2_V6_RESULTS"] = str(out / "adversarial_results.json")
    adv_env["M1_EXECUTION_PATH"] = str(out / "adversarial_execution.json")
    adv_env["M1_RUN_ID"] = out.name + "-adversarial"
    adv = subprocess.run([sys.executable, "-m", "pytest", *V6_SECOND_STAGE_NODEIDS, "-q"], cwd=root, capture_output=True, text=True, env=adv_env)
    (out / "adversarial_pytest.txt").write_text(adv.stdout + "\n" + adv.stderr)
    if adv.returncode != 0 or not (out / "adversarial_results.json").is_file():
        print(adv.stdout)
        print(adv.stderr)
        raise SystemExit(adv.returncode or 1)
    again = collect_inputs(root)
    if again != after:
        raise SystemExit("shared inputs changed during adversarial checks")
    (out / "run.json").write_text(json.dumps({"incomplete": False, "scope": SCOPE_NAME, "m3_ready": False}, indent=2))
    (out / "evidence_manifest.json").write_text(json.dumps(_evidence_manifest(out), indent=2))
    verdict = evaluate_evidence(out, check_workspace=True)
    report = {
        "schema_version": SCHEMA_VERSION,
        "scope": SCOPE_NAME,
        "release_scoring_version": RELEASE_SCORING_VERSION,
        "incomplete": False,
        "fixes_passed": verdict["fixes_passed"],
        "m3_ready": False,
        "hybrid_force_status": "disabled",
        "evidence_valid": verdict["evidence_valid"],
        "remaining_m2_requirements": verdict["remaining_m2_requirements"],
        "reasons": verdict["reasons"],
        "pytest_returncode": proc.returncode,
        "adversarial_returncode": adv.returncode,
    }
    (out / "report.json").write_text(json.dumps(report, indent=2))
    print(json.dumps({"pytest": proc.returncode, "adversarial": adv.returncode, "output": str(out), "fixes_passed": verdict["fixes_passed"], "m3_ready": False, "reasons": verdict["reasons"][:12]}, indent=2))
    if not verdict["fixes_passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
